import "../globals.css";
import "../styles.css";

export const metadata = {
  title: "MyQuickLoan | Loan Application",
  description: "Generated by create next app",
};

export default function LoanProcessLayout({ children }) {
  return <main>{children}</main>;
}
